export { default as InvestorPersonalInformationFormDataType } from "./investor-personal-information";
export { default as CorporateInvestor } from "./corporate-investor";
export { default as DiasporaInvestor } from "./diaspora-investor";
export { default as IndividualInvestor } from "./individual-investor";
export { default as InvestorBasicInformation } from "./investor-basic-information";
export { default as InvestorPersonalInformation } from "./investor-personal-information";
export { default as InvestorsProfileSetup } from "./investors-profile-setup";
export { default as NonEthiopianInvestor } from "./non-ethiopian-investor";
export { default as InvestorPersonalPreferences } from "./investors-personal-preferences";
